modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0 License"

[[mods]]
modId = "aether"
version = "${file.jarVersion}"
displayName = "The Aether"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-aether"
logoFile = "aether.png"
credits = "Credits go to Gilded Games for maintaining the Aether mod, the Aether Collaboration Team (Kingbdogz, Shockah, Kodaichi, Flan, and 303) for creating the original Aether mod, Modding Legacy (115kino, KingPhygieBoo, and Lachney) for originally porting and developing the mod in newer versions, and GitHub contributors for their help throughout development."
authors = "bconlon, Burning Cactus, Drullkus, Hugo Payn, Jaryt, Oscar Payn, quek, Raptor, reetam"
description = '''
    Gilded Games presents the original Aether mod! Up to date for modern Minecraft versions and fully compatible with multiplayer. The Aether is a dimension of floating islands high in the sky, where you can begin a new survival adventure packed with new ores, mythical creatures and perilous Dungeons! All you need to do is construct a Glowstone frame and add water to light the mystical portal, and once you step in you’ll be transported immediately to the luscious hostile paradise of the Aether!'''

[[dependencies.aether]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.0.8,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.19.2-,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2]"
    ordering = "NONE"
    side = "BOTH"
